### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by pavelskipenes** [Sigevio/ntnui-swimming-frontend#20]
please create this file
`.github/workflows/build.yml`
```yml
name: Build CI

on: [pr, push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install yarn && yarn install
    - name: build site
      run: yarn run build
    - name: create exportable build
      run: yarn run export
```
cannot push because of an issue
```
git push --set-upstream origin CI
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 730 bytes | 730.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Sigevio/ntnui-swimming-frontend.git
To https://github.com/sigevio/org.ntnu.svommer.git
 ! [remote rejected] CI -> CI (refusing to allow an OAuth App to create or update workflow `.github/workflows/build.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/sigevio/org.ntnu.svommer.git'
```

Edit: Apparently I was really tired yesterday and quoted console log instead of the yml file :P hopefully this works :crossed_fingers:
